services:
  db:
    image: mysql:8.0
    container_name: fortbildungen_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "0.0.0.0:${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fortbildungen_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fortbildungen_server
    ports:
      - "0.0.0.0:${SERVER_PORT}:3000"
    #volumes:
    #  - ./backend:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - SERVER_URL=${SERVER_URL}
      - SERVER_PORT=${SERVER_PORT}
      - AD_URL=${AD_URL}
      - AD_BASE_DN=${AD_BASE_DN}
      - AD_DOMAIN=${AD_DOMAIN}
      - AD_NETBIOS_DOMAIN=${AD_NETBIOS_DOMAIN}
      - AD_BIND_DN=${AD_BIND_DN}
      - AD_BIND_PASSWORD=${AD_BIND_PASSWORD}
      - AD_ADMIN_GROUPS=${AD_ADMIN_GROUPS}
      - AD_DEBUG=${AD_DEBUG}
    networks:
      - fortbildungen_network

volumes:
  mysql_data:

networks:
  fortbildungen_network:
    driver: bridge
