version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: fortbildung_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fortbildung_db
      MYSQL_USER: manager
      MYSQL_PASSWORD: manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
