services:
  db:
    image: mysql:8.0
    container_name: fortbildung_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fortbildung_server
    ports:
      - "${SERVER_PORT}:3000"
    #volumes:
    #  - ./backend:/app
    environment:
      - NODE_ENV=production

volumes:
  mysql_data:
